# Perfil de desarrollo - Conectar a bases de datos en Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/chatbot_colegio
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hot reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false
spring.resources.cache-period=0
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update