# Perfil de desarrollo - Conectar a bases de datos en Docker
spring.datasource.url=jdbc:postgresql://localhost:5434/sistema_academico
spring.datasource.username=postgres
spring.datasource.password=admin

# Hot reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false
spring.resources.cache-period=0
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update